[package]
name = "tmux-thumbs"
version = "0.1.0"
authors = ["Ferran Basora <fcsonline@gmail.com>"]
edition = "2018"
description = "A lightning fast version of tmux-fingers, copy/pasting tmux like vimium/vimperator"
repository = "https://github.com/fcsonline/tmux-thumbs"
keywords = ["rust", "tmux", "tmux-plugin", "vimium", "vimperator"]
license = "MIT"

[dependencies]
rustbox = "*"
regex = "1"
clap = "2.32.0"
